# Generated by Django 3.2.16 on 2022-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partygroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
