# Generated by Django 3.2.16 on 2022-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_partygroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
