# Generated by Django 3.2.16 on 2022-11-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_bank_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='bankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bank'),
        ),
        migrations.AddField(
            model_name='collection',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
