# Generated by Django 3.2.16 on 2022-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_auto_20221114_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.FloatField(default=0)),
                ('used', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'g) Geolocation Package List',
            },
        ),
    ]
