# Generated by Django 3.2.16 on 2022-11-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0005_geolocationpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceID', models.CharField(blank=True, max_length=300, null=True)),
                ('apiKey', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=0)),
                ('used', models.FloatField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
