# Generated by Django 3.2.16 on 2022-11-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0006_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='assignTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='home.staffuser'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
