# Generated by Django 3.2.16 on 2022-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0007_auto_20221128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='paymentID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
