# Generated by Django 3.2.16 on 2022-12-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_collection_paymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ApprovedBy', to='home.staffuser'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='bankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bank'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collectedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CollectedBy', to='home.staffuser'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='partyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.party'),
        ),
        migrations.AlterField(
            model_name='party',
            name='assignTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.staffuser'),
        ),
        migrations.AlterField(
            model_name='party',
            name='partyGroupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.partygroup'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='partyGroupID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.partygroup'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='user_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
