# Generated by Django 3.2.16 on 2022-12-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221201_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
