# Generated by Django 3.2.16 on 2023-01-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sales_whatsappmessagestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'K) Sales List'},
        ),
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'verbose_name_plural': 'L) Whatsapp Message Package List'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdByStaff', to='home.staffuser'),
        ),
    ]
