# Generated by Django 3.2.16 on 2023-01-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230107_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='chequeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SalesApprovedBy', to='home.staffuser'),
        ),
        migrations.AddField(
            model_name='sales',
            name='approvedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
