# Generated by Django 3.2.16 on 2023-08-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230114_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='transferredPartyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TransferredPartyID', to='home.party'),
        ),
    ]
