# Generated by Django 3.2.16 on 2023-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_collection_transferredpartyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='isTallied',
            field=models.BooleanField(default=True),
        ),
    ]
