# Generated by Django 3.2.16 on 2024-02-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_collection_istallied'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterID', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('mode', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('mixCashAmount', models.FloatField(default=0.0)),
                ('mixCardAmount', models.FloatField(default=0.0)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('entryDate', models.DateTimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdByStaffCashCounter', to='home.staffuser')),
                ('partyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.party')),
            ],
            options={
                'verbose_name_plural': 'L) Cash Counter List',
            },
        ),
    ]
