# Generated by Django 3.2.16 on 2024-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_cashcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcounter',
            name='expenseType',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
