# Generated by Django 3.2.16 on 2024-03-17 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cashcounter_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcounter',
            name='bankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bank'),
        ),
    ]
