# Generated by Django 3.2.16 on 2024-03-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_cashcounter_bankid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCashCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(blank=True, max_length=200, null=True)),
                ('modeOfPayment', models.CharField(default='Cash', max_length=200)),
                ('paidAmount', models.FloatField(default=0.0)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('collectionAddress', models.TextField(blank=True, null=True)),
                ('approvedOn', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.CharField(default='0.0', max_length=200)),
                ('longitude', models.CharField(default='0.0', max_length=200)),
                ('isApproved', models.BooleanField(default=False)),
                ('isTallied', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('collectionDateTime', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('chequeDate', models.DateField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CashCounterApprovedBy', to='home.staffuser')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bank')),
                ('collectedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CashCounterCollectedBy', to='home.staffuser')),
                ('partyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.party')),
                ('transferredPartyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CashCounterTransferredPartyID', to='home.party')),
            ],
            options={
                'verbose_name_plural': 'f) Cash Counter Collection List',
            },
        ),
    ]
