# Generated by Django 3.2.16 on 2026-02-24 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_collectioncashcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
